# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/roll_out_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/roll_out_service.proto',
  package='evolution_algorithms',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fprotobuf/roll_out_service.proto\x12\x14\x65volution_algorithms\"#\n\rCMAParameters\x12\x12\n\nparameters\x18\x01 \x03(\x01\"\x89\x01\n\x0eRollOutRequest\x12\x16\n\x0eroll_out_index\x18\x01 \x01(\x05\x12\x10\n\x08\x65nv_seed\x18\x02 \x01(\x05\x12\x10\n\x08\x65valuate\x18\x03 \x01(\x08\x12;\n\x0e\x63ma_parameters\x18\x04 \x01(\x0b\x32#.evolution_algorithms.CMAParameters\":\n\x0fRollOutResponse\x12\x16\n\x0eroll_out_index\x18\x01 \x01(\x05\x12\x0f\n\x07\x66itness\x18\x02 \x01(\x01\"\x12\n\x10ParamSyncRequest\"\'\n\x11ParamSyncResponse\x12\x12\n\nparameters\x18\x01 \x03(\x01\x32q\n\x0eRollOutService\x12_\n\x0eperformRollOut\x12$.evolution_algorithms.RollOutRequest\x1a%.evolution_algorithms.RollOutResponse\"\x00\x32z\n\x14ParameterSyncService\x12\x62\n\rsyncParameter\x12&.evolution_algorithms.ParamSyncRequest\x1a\'.evolution_algorithms.ParamSyncResponse\"\x00\x62\x06proto3')
)




_CMAPARAMETERS = _descriptor.Descriptor(
  name='CMAParameters',
  full_name='evolution_algorithms.CMAParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameters', full_name='evolution_algorithms.CMAParameters.parameters', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=92,
)


_ROLLOUTREQUEST = _descriptor.Descriptor(
  name='RollOutRequest',
  full_name='evolution_algorithms.RollOutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll_out_index', full_name='evolution_algorithms.RollOutRequest.roll_out_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='env_seed', full_name='evolution_algorithms.RollOutRequest.env_seed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='evaluate', full_name='evolution_algorithms.RollOutRequest.evaluate', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cma_parameters', full_name='evolution_algorithms.RollOutRequest.cma_parameters', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=232,
)


_ROLLOUTRESPONSE = _descriptor.Descriptor(
  name='RollOutResponse',
  full_name='evolution_algorithms.RollOutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll_out_index', full_name='evolution_algorithms.RollOutResponse.roll_out_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='evolution_algorithms.RollOutResponse.fitness', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=292,
)


_PARAMSYNCREQUEST = _descriptor.Descriptor(
  name='ParamSyncRequest',
  full_name='evolution_algorithms.ParamSyncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=312,
)


_PARAMSYNCRESPONSE = _descriptor.Descriptor(
  name='ParamSyncResponse',
  full_name='evolution_algorithms.ParamSyncResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameters', full_name='evolution_algorithms.ParamSyncResponse.parameters', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=353,
)

_ROLLOUTREQUEST.fields_by_name['cma_parameters'].message_type = _CMAPARAMETERS
DESCRIPTOR.message_types_by_name['CMAParameters'] = _CMAPARAMETERS
DESCRIPTOR.message_types_by_name['RollOutRequest'] = _ROLLOUTREQUEST
DESCRIPTOR.message_types_by_name['RollOutResponse'] = _ROLLOUTRESPONSE
DESCRIPTOR.message_types_by_name['ParamSyncRequest'] = _PARAMSYNCREQUEST
DESCRIPTOR.message_types_by_name['ParamSyncResponse'] = _PARAMSYNCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CMAParameters = _reflection.GeneratedProtocolMessageType('CMAParameters', (_message.Message,), dict(
  DESCRIPTOR = _CMAPARAMETERS,
  __module__ = 'protobuf.roll_out_service_pb2'
  # @@protoc_insertion_point(class_scope:evolution_algorithms.CMAParameters)
  ))
_sym_db.RegisterMessage(CMAParameters)

RollOutRequest = _reflection.GeneratedProtocolMessageType('RollOutRequest', (_message.Message,), dict(
  DESCRIPTOR = _ROLLOUTREQUEST,
  __module__ = 'protobuf.roll_out_service_pb2'
  # @@protoc_insertion_point(class_scope:evolution_algorithms.RollOutRequest)
  ))
_sym_db.RegisterMessage(RollOutRequest)

RollOutResponse = _reflection.GeneratedProtocolMessageType('RollOutResponse', (_message.Message,), dict(
  DESCRIPTOR = _ROLLOUTRESPONSE,
  __module__ = 'protobuf.roll_out_service_pb2'
  # @@protoc_insertion_point(class_scope:evolution_algorithms.RollOutResponse)
  ))
_sym_db.RegisterMessage(RollOutResponse)

ParamSyncRequest = _reflection.GeneratedProtocolMessageType('ParamSyncRequest', (_message.Message,), dict(
  DESCRIPTOR = _PARAMSYNCREQUEST,
  __module__ = 'protobuf.roll_out_service_pb2'
  # @@protoc_insertion_point(class_scope:evolution_algorithms.ParamSyncRequest)
  ))
_sym_db.RegisterMessage(ParamSyncRequest)

ParamSyncResponse = _reflection.GeneratedProtocolMessageType('ParamSyncResponse', (_message.Message,), dict(
  DESCRIPTOR = _PARAMSYNCRESPONSE,
  __module__ = 'protobuf.roll_out_service_pb2'
  # @@protoc_insertion_point(class_scope:evolution_algorithms.ParamSyncResponse)
  ))
_sym_db.RegisterMessage(ParamSyncResponse)



_ROLLOUTSERVICE = _descriptor.ServiceDescriptor(
  name='RollOutService',
  full_name='evolution_algorithms.RollOutService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=355,
  serialized_end=468,
  methods=[
  _descriptor.MethodDescriptor(
    name='performRollOut',
    full_name='evolution_algorithms.RollOutService.performRollOut',
    index=0,
    containing_service=None,
    input_type=_ROLLOUTREQUEST,
    output_type=_ROLLOUTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROLLOUTSERVICE)

DESCRIPTOR.services_by_name['RollOutService'] = _ROLLOUTSERVICE


_PARAMETERSYNCSERVICE = _descriptor.ServiceDescriptor(
  name='ParameterSyncService',
  full_name='evolution_algorithms.ParameterSyncService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=470,
  serialized_end=592,
  methods=[
  _descriptor.MethodDescriptor(
    name='syncParameter',
    full_name='evolution_algorithms.ParameterSyncService.syncParameter',
    index=0,
    containing_service=None,
    input_type=_PARAMSYNCREQUEST,
    output_type=_PARAMSYNCRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARAMETERSYNCSERVICE)

DESCRIPTOR.services_by_name['ParameterSyncService'] = _PARAMETERSYNCSERVICE

# @@protoc_insertion_point(module_scope)
